### ISSUE TITLE
[CI] Parallelize travis jobs

### ISSUE THREAD

**Issue by kirjs** [codelab-fun/codelab#1135]
# What the issue is about
Right now we're running lint + aot build (+ soon test + format) consequently.
https://github.com/codelab-fun/codelab/blob/master/.travis.yml#L12

They are completely independent and could potentially be run in parallel

# How to start
Get travis-ci access from kirjs, and google how to run travis tasks in parallel

**Comment by Mutmatt** [comment]
I did a quick POC of what i _think_ should run these in parallel but the results were slightly less than exciting. I can submit the PR if you'd like it because i know the testing will make the time spike more. Right now a majority of your build is bringing up the container.

![Screen Shot 2019-10-18 at 2 39 07 PM](https://user-images.githubusercontent.com/872224/67123140-111d0580-f1b5-11e9-93ec-6b4561800b9b.png)
![Screen Shot 2019-10-18 at 2 38 59 PM](https://user-images.githubusercontent.com/872224/67123141-111d0580-f1b5-11e9-9272-20e216ce341e.png)

Ref: https://github.com/Mutmatt/codelab/commit/0b6ae04

**Comment by NothingEverHappens** [comment]
Oh, wow, this is amazing, 20% faster is a great start!
The impact would be much higher once we start running tests in CI (which we don't do yet)

I also have some ideas for how to speed up the AOT part, which is taking most ATM
